language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO=django==1.4.*
    - DJANGO=django==1.6.*
    - DJANGO=django==1.7.*
    - DJANGO=django==1.8.*
    - DJANGO=django==1.9.*

sudo: false

install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install $DJANGO
    - pip install coveralls
    - pip install pytz

script:
    coverage run manage.py test

after_success:
    coveralls

matrix:
    exclude:
        - python: "3.4"
          env: DJANGO=django==1.4.*
        - python: "3.5"
          env: DJANGO=django==1.4.*
        - python: "3.5"
          env: DJANGO=django==1.6.*
        - python: "3.5"
          env: DJANGO=django==1.7.*
    allow_failures:
        - env: DJANGO=django==1.4.*
        - env: DJANGO=django==1.6.*
    fast_finish: true
