# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinghours', '0002_auto_20170915_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='UTC', max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
